"""update table product

Revision ID: d84496413daa
Revises: 9c4f35cd88a4
Create Date: 2024-06-13 00:24:17.315433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84496413daa'
down_revision: Union[str, None] = '9c4f35cd88a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_blacklisted_token_uid'), 'blacklisted_token', ['uid'])
    op.alter_column('product', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('uq_blacklisted_token_uid'), 'blacklisted_token', type_='unique')
    # ### end Alembic commands ###
